services:

  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_DEFAULT_REGION: 'us-east-2'
      MYSQL_DATABASE: 'drupal'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_HOST: 'mysql'
      S3_BACKUP_LOCATION: '/var/www/html/backups0test'
      DRUPAL_DATABASE_HOST: mysql
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USERNAME: ${MYSQL_USER}
      DRUPAL_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - composer_cache:/root/.composer/cache
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_sites:/var/www/html/sites
      - drupal_themes:/var/www/html/themes
      - ./opsportal:/var/www/html/opsportal
      - ./files/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./backups:/var/www/html/backups
      - ./backup-scripts:/opt/backup-scripts
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drupal.rule=Host(`drupal.localhost`)"
      - "traefik.http.routers.drupal.entrypoints=web,websecure"
      - "traefik.http.services.drupal.loadbalancer.server.port=80"
      - "traefik.http.routers.drupal.tls.certresolver=myresolver"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/core/install.php"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      mysql:
        condition: service_healthy
    cpu_shares: 512
    mem_limit: 2g
    networks:
      - drupal_network
    command: >
        bash -c "
          chown -R www-data:www-data /var/www/html &&
          chmod -R 755 /var/www/html
        "
    entrypoint: >
      bash -c "
        # Wait for MySQL to be ready
        while ! nc -z mysql 3306; do
          sleep 1
        done

        # Start Apache in background
        apache2-foreground &

        # Wait for Drupal files to be accessible
        until [ -f /var/www/html/sites/default/settings.php ]; do
          sleep 1
        done

        # Run Drupal-specific commands
        drush theme:enable operations_drupal_theme &&
        drush config-set system.theme default operations_drupal_theme -y &&

        # Keep container running
        supervisord -n
      "

  mysql:
    image: mysql:latest
    restart: always
    labels:
      - "traefik.enable=false"
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'drupal'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-backups:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    cpu_shares: 512
    mem_limit: 2g
    networks:
      - drupal_network

  phpmyadmin:
      image: arm64v8/phpmyadmin:latest
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"
        - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
        - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"
      restart: always
      environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - UPLOAD_LIMIT=300M
        - MAX_EXECUTION_TIME=600
      healthcheck:
        test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:80/"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 30s
      depends_on:
        mysql:
          condition: service_healthy
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 256M
      networks:
        - drupal_network

  traefik:
    image: traefik:v3.0
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
      - "--api.dashboard=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=jelambe@iu.edu"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    networks:
      - drupal_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`URL`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"

networks:
  drupal_network:
    name: drupal_network

volumes:
  composer_cache:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  drupal_themes:
  mysql-data:
